### ISSUE TITLE
runing the highway_planning.ipynb with some error

### ISSUE THREAD

**Issue by sjtulhm** [Farama-Foundation/HighwayEnv#442]
dear eleurent, i'm a new bird in python, when i run the highway_planning.ipynb, some errors exist.
"from utils import record_videos, show_videos" this code has the warn: Cannot find reference 'record_videos' in 'imported module utils'
the following is the error:
D:\anaconda\python.exe C:\Users\sjtulhm\PycharmProjects\pythonProject\test.py 
Traceback (most recent call last):
  File "C:\Users\sjtulhm\PycharmProjects\pythonProject\test.py", line 15, in <module>
    from utils import record_videos, show_videos
  File "C:\Users\sjtulhm\highway-env\scripts\utils.py", line 8, in <module>
    display = Display(visible=0, size=(1400, 900))
  File "D:\anaconda\lib\site-packages\pyvirtualdisplay\display.py", line 54, in __init__
    self._obj = cls(
  File "D:\anaconda\lib\site-packages\pyvirtualdisplay\xvfb.py", line 44, in __init__
    AbstractDisplay.__init__(
  File "D:\anaconda\lib\site-packages\pyvirtualdisplay\abstractdisplay.py", line 85, in __init__
    helptext = get_helptext(program)
  File "D:\anaconda\lib\site-packages\pyvirtualdisplay\util.py", line 13, in get_helptext
    p = subprocess.Popen(
  File "D:\anaconda\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\anaconda\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
![捕获](https://user-images.githubusercontent.com/126771770/228135001-e32a5f52-03c8-4d4c-b308-1ae85cfd0dc2.PNG)
![捕获2](https://user-images.githubusercontent.com/126771770/228135193-94824877-0c84-4045-85cf-23dd71caa829.PNG)
thank you!

**Comment by eleurent** [comment]
Hi,
You probably copied the code for the notebooks, they import the utils.py script is located here:

https://github.com/Farama-Foundation/HighwayEnv/blob/master/scripts/utils.py

So you can just download it :)

**Comment by eleurent** [comment]
otherwise you can also just remove the call to `show_videos` and replace `record_videos` by
```
    env = RecordVideo(env, video_folder=video_folder, episode_trigger=lambda e: True)
    # Capture intermediate frames
    env.unwrapped.set_record_video_wrapper(env)
```
