### ISSUE TITLE
 A question about version

### ISSUE THREAD

**Issue by huang6668** [Farama-Foundation/HighwayEnv#465]
When I use version 1.4.0, an error occurs when running the code in the "Getting Started" guide, as follows:
Traceback (most recent call last):
  File "C:\Users\11648\Documents\MyProject\multi_agent\test.py", line 5, in <module>
    env = gym.make('highway-v0')
  File "C:\Users\11648\.conda\envs\marl\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\11648\.conda\envs\marl\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\11648\.conda\envs\marl\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "C:\Users\11648\.conda\envs\marl\lib\site-packages\highway_env\envs\common\abstract.py", line 84, in __init__
    self.reset()
  File "C:\Users\11648\.conda\envs\marl\lib\site-packages\highway_env\envs\common\abstract.py", line 191, in reset
    self._reset(num_CAV=num_CAV)
TypeError: _reset() got an unexpected keyword argument 'num_CAV'

**Comment by huang6668** [comment]
This is the code I ran:
import gym
import highway_env
from matplotlib import pyplot as plt

env = gym.make('highway-v0')
env.reset()

for _ in range(10):
    action = env.action_type.actions_indexes["IDLE"]
    obs, reward, down, info = env.step(action)
    env.render()
plt.imshow(env.render(mode="rgb_array"))
plt.show()
