### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/logging.json'

### ISSUE THREAD

**Issue by thyagt** [Farama-Foundation/HighwayEnv#488]
```
!python /content/rl-agents/scripts/experiments.py evaluate /content/rl-agents/scripts/configs/HighwayEnv/env_multi_agent.json \
                               /content/rl-agents/scripts/configs/HighwayEnv/agents/DQNAgent/dqn.json \
                               --train --episodes=3000
                               
```
@eleurent 

I am running this script to train multi agent but I am getting FileNotFound error,

Traceback (most recent call last):
  File "/content/rl-agents/scripts/experiments.py", line 148, in <module>
    main()
  File "/content/rl-agents/scripts/experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "/content/rl-agents/scripts/experiments.py", line 56, in evaluate
    logger.configure(LOGGING_CONFIG)
  File "/root/.local/lib/python3.10/site-packages/rl_agents/trainer/logger.py", line 50, in configure
    with Path(config).open() as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'configs/logging.json'

**Comment by eleurent** [comment]
Hi, 
You need to cd to the /path/to/script directory, as the configs paths are relative to there.
