### ISSUE TITLE
Issues with training in the intersection.env environment

### ISSUE THREAD

**Issue by Denwey1** [Farama-Foundation/HighwayEnv#519]
When I train using raw merge-v0 environment, I receive the following error： I don’t know what caused this, could anyone help me?

home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/gymnasium/utils/passive_env_checker.py:43: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (5, 5)
  "A Box observation space has an unconventional shape (neither an image, nor a 1D vector). "
Traceback (most recent call last):
  File "/home/ted/文档/PythonProjects/continualworld_highway/run_single.py", line 62, in <module>
    main(logger, **args)
  File "/home/ted/文档/PythonProjects/continualworld_highway/run_single.py", line 53, in main
    sac.run()
  File "/home/ted/文档/PythonProjects/continualworld_highway/continualworld/sac/sac.py", line 546, in run
    obs, info = self.env.reset()
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/gymnasium/wrappers/env_checker.py", line 55, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/gymnasium/utils/passive_env_checker.py", line 215, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/highway_env/envs/common/abstract.py", line 208, in reset
    info = self._info(obs, action=self.action_space.sample())
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/highway_env/envs/common/abstract.py", line 181, in _info
    info["rewards"] = self._rewards(action)
  File "/home/ted/anaconda3/envs/continualworld/lib/python3.7/site-packages/highway_env/envs/merge_env.py", line 58, in _rewards
    "high_speed_reward": self.vehicle.speed_index / (self.vehicle.target_speeds.size - 1),
AttributeError: 'Vehicle' object has no attribute 'speed_index'

Process finished with exit code 1

**Comment by eleurent** [comment]
Should be fixed
